package it.revo.revoservice.entity.enums;

public enum DarsVaqti {
    SAKKIZDAN_10GACHA, ONDAN_12GACHA, ONIKKIDAN_14GACHA, ONTORTDAN_16GACHA, ONOLTIDAN_18GACHA, ONSAKKIZDAN_20GACHA, YIGIRMADAN_22GACHA
}